// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, cookieParser, db, express, fs, logger, mongo, mongoose, routes, server, tag;

  tag = "index:%s =>";

  fs = require("fs");

  express = require("express");

  logger = require("morgan");

  bodyParser = require("body-parser");

  cookieParser = require("cookie-parser");

  mongoose = require("mongoose");

  routes = require("./router");

  db = require("./db");

  mongo = "mongodb://localhost/daytimer";

  mongoose.connect(mongo);

  app = express();

  app.use(logger("dev"));

  app.use(bodyParser.raw());

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(express["static"]("./ui"));

  app.set("views", "dev/ui/jade");

  app.set("view engine", "jade");

  routes(app);

  db(app);

  server = app.listen(2000, function(req, res) {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    if (host === "::") {
      host = "localhost";
    }
    return console.log("Daytimer listening at http://%s:%s", host, port);
  });

}).call(this);
