// Generated by CoffeeScript 1.10.0
(function() {
  var DaytimerSchema, QuestionSchema, Schema, mongoose, tag;

  tag = "models:%s =>";

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  QuestionSchema = new Schema({
    type: String,
    category: String,
    question: String,
    frequency: Number,
    min: Number,
    timeRange: Number,
    goal: Number,
    dateLastAnswered: Date,
    refs: []
  });

  DaytimerSchema = new Schema({
    questionRef: String,
    date: Date,
    complete: Boolean,
    start: Date,
    end: Date
  });

  mongoose.model("Question", QuestionSchema);

  mongoose.model("Daytimer", DaytimerSchema);

}).call(this);
