// Generated by CoffeeScript 1.10.0
(function() {
  var exports, home, r, tag;

  tag = "router:%s =>";

  home = function(req, res) {
    return res.render("index");
  };

  r = function(app) {
    app.get("/", home);
    app.get("/trackers", home);
    app.get("/stats", home);
    app.get("/dashboard", home);
    return app.get("/settings", home);
  };

  exports = module.exports = r;

}).call(this);
