// Generated by CoffeeScript 1.10.0
(function() {
  var exports, index, nav, questions, tag;

  tag = "react/index:%s =>";

  questions = require("./questions");

  nav = require("./nav");

  index = {
    questions: questions,
    nav: nav
  };

  module.exports = exports = index;

}).call(this);
