// Generated by CoffeeScript 1.10.0
(function() {
  var exports, index, questions, tag;

  tag = "react/index:%s =>";

  questions = require("./questions");

  index = {
    questions: questions
  };

  module.exports = exports = index;

}).call(this);
