// Generated by CoffeeScript 1.10.0
(function() {
  var dashboard, exports, index, list, questions, settings, stats, tag, trackers;

  tag = "react/index:%s =>";

  dashboard = require("./dashboard");

  list = require("./questions");

  stats = require("./stats");

  settings = require("./settings");

  trackers = require("./trackers");

  questions = require("./questions");

  index = {
    trackers: trackers,
    dashboard: dashboard,
    stats: stats,
    settings: settings,
    widgets: {
      questions: questions
    }
  };

  module.exports = exports = index;

}).call(this);
